[package]
name = "dao-political-meta"
version = "0.1.0"
authors = ["DEMOCRATIX Team"]
edition = "2021"
publish = false

[dependencies.dao-political]
path = ".."

[dependencies.multiversx-sc-meta-lib]
version = "0.62.0"

[dev-dependencies]
num-bigint = "0.4"
