[package]
name = "poll-meta"
version = "0.0.0"
edition = "2021"
publish = false

[[bin]]
name = "poll-meta"
path = "src/main.rs"

[dependencies.poll]
path = ".."

[dependencies.multiversx-sc-meta-lib]
version = "0.62"
