[package]
name = "ric-meta"
version = "0.0.0"
edition = "2021"
publish = false

[[bin]]
name = "ric-meta"
path = "src/main.rs"

[dependencies.ric]
path = ".."

[dependencies.multiversx-sc-meta-lib]
version = "0.62"
