[package]
name = "poll"
version = "0.1.0"
authors = ["DEMOCRATIX Team"]
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"

[dependencies]
multiversx-sc = "0.62"

[dev-dependencies]
multiversx-sc-scenario = "0.62"
