[package]
name = "voter-registry"
version = "0.1.0"
authors = ["DEMOCRATIX Contributors"]
edition = "2021"
publish = false

[dependencies]
multiversx-sc = "0.53"

[dev-dependencies]
multiversx-sc-scenario = "0.53"
